server {
    listen       3602;
    listen  [::]:3602;
    server_name  neuroviewer;  
   
   location /neuroviewer/ {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /neuroviewer/index.html;
    }

    #location ~* \.(js|jpg|png|css)$ {
    #    root /usr/share/nginx/html/neuroviewer/;
    #}

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}