server {
    listen       3603;
    listen  [::]:3603;
    server_name  neuroviewer; 
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
    add_header Access-Control-Allow-Headers "Content-Type, Accept, Authorization";
    add_header Access-Control-Expose-Headers "Origin";
   
    location /neuroviewer/ {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /neuroviewer/index.html;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, Accept, Authorization";
        add_header Access-Control-Expose-Headers "Origin";
    }

    location /neuroviewer/https://www.wikipedia.org/ {
        # add_header Access-Control-Allow-Origin *;
        # add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        # add_header Access-Control-Allow-Headers "Content-Type, Accept, Authorization";
        # add_header Access-Control-Expose-Headers "Origin";
        # add_header Access-Control-Allow-Credentials "true";
    }

    location / {
        # add_header Access-Control-Allow-Origin *;
        # add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        # add_header Access-Control-Allow-Headers "Content-Type, Accept, Authorization";
        # add_header Access-Control-Expose-Headers "Origin";
        # add_header Access-Control-Allow-Credentials "true";
    }

    location /https://www.wikipedia.org/ {
        # add_header Access-Control-Allow-Origin *;
        # add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        # add_header Access-Control-Allow-Headers "Content-Type, Accept, Authorization";
        # add_header Access-Control-Expose-Headers "Origin";
        # add_header Access-Control-Allow-Credentials "true";
    }



    #location ~* \.(js|jpg|png|css)$ {
    #    root /usr/share/nginx/html/neuroviewer/;
    #}

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}