version: '3.7'

networks:
  local:

services:
    connectivity:
        container_name: neuroviewer-app
        build:
                context: .
                dockerfile: Dockerfile
        ports:
        - 8000:8000